baseURL = "https://gomex.me/"
languageCode = "en-US"
title = "Rafael Gomex"
# Enable comments by entering your Disqus shortname
disqusShortname = "gomex-me-1"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpeg"
  author = "Gomex"
  description = "Conhecimento retido Ã© conhecimento perdido"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "gomex"
  Email         = "me@gomex.me"
  Twitter       = "gomex"
  LinkedIn      = "rbgomes"
  Stackoverflow = "gomex"
  Medium        = "gomex"
  Telegram      = "gomex"
  RSS           = "/blog/index.xml"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "mentoria iac"
  identifier = "mentoriaiac"
  weight = 200
  url = "/mentoriaiac/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "https://gomex.github.io/"
